version: '3.4'

services:
  new:
    build:
      context: .
      dockerfile: Dockerfile
      target: base

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    command: >
      sh -c "yarn install &&
            yarn develop -H 0.0.0.0"
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/gatsby_js
      - /usr/src/gatsby_js/node_modules
